/** Stable names for Beacon's built-in UX and health signals. */
export const BEACON_SIGNAL = {
  AUTH_FAILURE_STORM: "auth_failure_storm",
  BROWSER_INTERVENTION: "browser_intervention",
  BROWSER_POLICY_VIOLATION: "browser_policy_violation",
  BFCACHE_BLOCKED: "bfcache_blocked",
  CAPABILITY_FAILURE: "capability_failure",
  BLANK_APP_ROOT: "blank_app_root",
  CONSOLE_ERROR: "console_error",
  CONTROL_COLLISION: "control_collision",
  CSP_VIOLATION: "csp_violation",
  CLIPBOARD_FAILURE: "clipboard_failure",
  DEAD_CLICK: "dead_click",
  DISRUPTIVE_LAYOUT_SHIFT: "disruptive_layout_shift",
  DOCUMENT_DISCARDED: "document_discarded",
  ERROR_CLICK: "error_click",
  FETCH_FAILED: "fetch_failed",
  FOCUS_LOST: "focus_lost",
  FONT_FAILURE: "font_failure",
  FORM_FRUSTRATION: "form_frustration",
  FORM_ABANDONMENT: "form_abandonment",
  FOCUSED_CONTROL_OFFSCREEN: "focused_control_offscreen",
  HTTP_5XX: "http_5xx",
  HTTP_RESPONSE_FAILURE: "http_response_failure",
  INVISIBLE_TEXT: "invisible_text",
  EMBEDDED_CONTENT_STALLED: "embedded_content_stalled",
  LAYOUT_OVERFLOW: "layout_overflow",
  MAIN_THREAD_STALL: "main_thread_stall",
  MEDIA_PLAYBACK_FAILED: "media_playback_failed",
  MEDIA_PLAYBACK_STALLED: "media_playback_stalled",
  MODAL_FOCUS_ESCAPE: "modal_focus_escape",
  OCCLUDED_CONTROL: "occluded_control",
  RAGE_CLICK: "rage_click",
  RATE_LIMITED: "rate_limited",
  NAVIGATION_STALLED: "navigation_stalled",
  RELOAD_LOOP: "reload_loop",
  REQUEST_STORM: "request_storm",
  SEMANTIC_RESPONSE_FAILURE: "semantic_response_failure",
  SCROLL_JAIL: "scroll_jail",
  SLOW_RESPONSE: "slow_response",
  SLOW_RESOURCE: "slow_resource",
  SLOW_INTERACTION: "slow_interaction",
  SOCKET_ABNORMAL_CLOSE: "socket_abnormal_close",
  SOCKET_FLAPPING: "socket_flapping",
  SSE_FLAPPING: "sse_flapping",
  STALE_RELEASE: "stale_release",
  STALLED_STREAM: "stalled_stream",
  STUCK_LOADING: "stuck_loading",
  THEME_MISMATCH: "theme_mismatch",
  THRASHED_CURSOR: "thrashed_cursor",
  STORAGE_FAILURE: "storage_failure",
  WEBGL_CONTEXT_LOST: "webgl_context_lost",
  SERVICE_WORKER_FAILURE: "service_worker_failure",
  WORKER_FAILURE: "worker_failure",
} as const;

export type BeaconSignal = (typeof BEACON_SIGNAL)[keyof typeof BEACON_SIGNAL];

/** Stable DOM attributes understood by Beacon's instrumentation. */
export const BEACON_ATTRIBUTE = {
  APP_ROOT: "data-beacon-app-root",
  CONTROL_GROUP: "data-beacon-control-group",
  DEAD_CLICK: "data-beacon-dead-click",
  NAME: "data-beacon-name",
  EMBED: "data-beacon-embed",
  LOADING: "data-beacon-loading",
  LOADING_TIMEOUT: "data-beacon-loading-timeout",
  FORM: "data-beacon-form",
  /** `="allow"` exempts an intentional dynamic subtree from layout-shift issues. */
  LAYOUT_SHIFT: "data-beacon-layout-shift",
  MEDIA: "data-beacon-media",
  OVERFLOW: "data-beacon-overflow",
  SCAN: "data-beacon-scan",
  THEME: "data-beacon-theme",
} as const;
